# PG setup:
#  createuser graph_kit_ruby --createdb
#  rake db:create db:migrate db:seed
#  env RAILS_ENV=test rake db:create db:migrate db:seed

#____________________________________________________________
# common
#____________________________________________________________

pg: &pg
  adapter:    postgresql
  encoding:   utf8
  template:   template0
  port:       5432
  pool:       25

#____________________________________________________________
# environments
#____________________________________________________________

development:
  <<: *pg
  host:         127.0.0.1
  username:     graph_kit_ruby
  password:     graph_kit_ruby
  database:     graph_kit_ruby_development

test: &test
  <<: *pg
  host:         127.0.0.1
  username:     graph_kit_ruby
  password:     graph_kit_ruby
  database:     graph_kit_ruby_test

production: &production
  <<: *pg
  host:         127.0.0.1
  username:     graph_kit_ruby
  password:     graph_kit_ruby
  database:     graph_kit_ruby_production
